config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   resources :articles, :path => "blog" do
   resources :comments

   end

  get 'users/profile', as: 'user_url'
  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #def after_sign_in_path_for(resource)
  #  user
  #end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

before_action :set_locale

def set_locale
  I18n.locale = params[:locale] || I18n.default_locale
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
	@article = Article.find(params[:id])
    end

    def new
	@article = Article.new
    end

    def index
    	@page_title = "Blog"
	@articles = Article.paginate(:page => params[:page], :per_page => 3)
    end

def edit
  @article = Article.find(params[:id])
end

def destroy
  @article = Article.find(params[:id])
  @article.destroy

  redirect_to articles_path
end

def update
  @article = Article.find(params[:id])

  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end

    def create
    	uploaded_io = params[:article][:image]
  	File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
    	file.write(uploaded_io.read)

  end

  	@article = Article.new(article_params)
	@article.image = "/uploads/#{uploaded_io.original_filename}"
  @article.save
  redirect_to @article
    end
end

private
def article_params
params.require(:article).permit(:title, :image, :overview, :text)
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@page_title = "Main Page"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    Kramdown::Document.new(text, :auto_ids => false).to_html
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
<fieldset>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.label :title %><br>
    <%= f.text_field :title %>

    <%= f.label :overview %><br>
    <%= f.text_area :overview %>

    <%= f.label :text %><br>
    <%= f.text_area :text %>
    <%= f.label :image %><br>
    <%= f.file_field :image %>

    <%= f.submit :class=>"small button" %>
</fieldset>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
 <%= link_to 'New article', new_article_path %>
<% @articles.each do |article| %>
<article>
<h3><a href="blog/<%= article.id %>"><%= article.title %></a></h3>
<div class="row">
<div class="large-6 columns">
Test
</div>
<div class="large-6 columns">
<img src="<%= article.image %>"/>
</div>
</div>
<%=raw article.overview %>
</article>
  <% end %>
<p>
<%= will_paginate @articles %>
</p>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<article>
<h3><a href="#"><%= @article.title %></a></h3>
<h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>
<div class="row">
<div class="large-6 columns">
Test
</div>
<div class="large-6 columns">
<img src="<%= @article.image %>"/>
</div>
</div>
<%=raw markdown(@article.text) %>
</article>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
<%= comment.commenter %>
</p>
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Delete Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    <div class="g-recaptcha" data-sitekey="6LeSNf4SAAAAAI-AAh7ZNmtAhRYHGpCPXfQyHDuW"></div>
  </p>
  <p>
    <%= f.submit :class=>"small button" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" data-useragent="Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Trident/6.0)">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title><%= @page_title %> | Unicode4all</title>
<meta name="description" content="Documentation and reference library for ZURB Foundation. JavaScript, CSS, components, grid and more."/>
<meta name="author" content="ZURB, inc. ZURB network also includes zurb.com"/>
<meta name="copyright" content="ZURB, inc. Copyright (c) 2015"/>
<script src='https://www.google.com/recaptcha/api.js'></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<link rel="stylesheet" href="/assets/foundation.css"/>
<link rel="stylesheet" href="/assets/style.css"/>
<script src="/assets/vendor/modernizr.js"></script>

</head>
<body>

<link href="http://fonts.googleapis.com/css?family=Raleway:600,400,200" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet" type="text/css">
<div class="row">
<div class="small-12 medium-4 large-6 columns namelogo">
<a href="/"><h1>Unicode <span style="text-decoration:line-through; font-size:7pt">not</span> For All</h1></a>
</div>
<div class="small-12 medium-8 large-6 columns">
<div class="nav-bar">
<ul class="button-group">
<li><a href="#" class="button"><%= t('About') %></a></li>
  <li><a href="/blog" class="button"><%= t('Blog') %></a></li>
</ul>
</div>
</div>
</div>
  <% if notice %>
  <div class="alert-box success">
  <%= notice %>
  <a href="" class="close">&times;</a>
</div>
    <% end %>
<% if alert %>
  <div class="alert-box alert">
  <%= alert %>
  <a href="" class="close">&times;</a>
</div>
<% end %>
<div class="row">
<%= yield %>
</div>
<div class="row contact">
<hr>
<div class="large-12 columns">
<h4>Contact Me</h4>
<div class="large-2 columns">
<strong>Email/Jabber</strong>: <a href="mailto:celestia@unicode4all.org">celestia@unicode4all.org</a>
</div>
</div>
</div>
<footer class="row">
<div class="large-12 columns">
<div class="row">
<div class="large-6 columns">
<p>© Copyright 2015 Unicode4all.</p>
</div>
<div class="large-6 columns">
<ul class="inline-list right">
<li><a href="#">Privacy</a></li>
</ul>
</div>
</div>
</div>
</footer>
<!--<script src="/assets/vendor/jquery.js"></script>-->
<script src="/assets/foundation.min.js"></script>
<script src="/assets/vendor/foundation/foundation.js"></script>
<script src="/assets/vendor/foundation/foundation.clearing.js"></script>
<script>
  $(document).foundation();
</script>
</body>
</html>
</html>

app/views/users/_form.html.erb
<%= form.label :login %><br />
<%= form.text_field :login %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : "Change password" %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />

app/views/users/edit.html.erb
<h1>Edit My Account</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<br /><%= link_to "My Profile", account_path %>

app/views/users/new.html.erb
<h1>Register</h1>

<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Register" %>
<% end %>

app/views/users/profile.html.erb
<h1>Users#profile</h1>
<p>Find me in app/views/users/profile.html.erb</p>

app/views/users/show.html.erb
<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>


<%= link_to 'Edit', edit_account_path %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
    <span>Здравствуйте, <%= current_user.email %></span>
    <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Войти', new_user_session_path %> или <%= link_to 'Зарегистрироваться', new_user_registration_path %>
<% end %>